import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';

const html=readFileSync(new URL('../public/commerce.html',import.meta.url),'utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];

test('commerce UI JavaScript parses and covers every requested channel',()=>{
  assert.doesNotThrow(()=>new vm.Script(script));
  for(const channel of ['amazon','taobao','pinduoduo','douyin','xiaohongshu']) assert.match(script,new RegExp(channel));
});
test('commerce UI provides persisted Chinese and English copy',()=>{
  assert.match(script,/localStorage\.getItem\('vco_lang'\)/);
  assert.match(script,/copy=\{zh:\{/);
  assert.match(script,/,en:\{/);
  assert.match(html,/id="language"/);
  assert.match(script,/orderId:'订单号'/);
  assert.match(script,/orderId:'Order'/);
  assert.match(script,/errorText=code/);
  assert.match(script,/authentication_required:'请先登录。'/);
});
test('commerce UI connects all operational controls to the authenticated API',()=>{
  for(const route of ['/api/commerce/shops','/api/commerce/imports','/api/commerce/summary','/api/commerce/orders']) assert.match(script,new RegExp(route));
  assert.match(script,/authorization:'Bearer '\+token/);
  assert.match(html,/id="csvFile"/);
  assert.match(html,/id="refreshImports"/);
  assert.match(script,/async function imports\(\)/);
  assert.match(script,/importHistory:'导入记录'/);
  assert.match(script,/importHistory:'Import history'/);
  assert.match(script,/shop:'店铺'/);
  assert.match(script,/shop:'Shop'/);
  assert.match(script,/x\.shop\.name/);
  assert.match(script,/async function orders\(\).*?x\.shop\?esc\(x\.shop\.name\)/);
  assert.match(html,/id="orderShop"/);
  assert.match(script,/allShops:'全部店铺'/);
  assert.match(script,/allShops:'All shops'/);
  assert.match(script,/p\.set\('shop_id',shop\)/);
  assert.match(html,/id="orderStatus"/);
  assert.match(script,/allStatuses:'全部原始状态'/);
  assert.match(script,/allStatuses:'All source statuses'/);
  assert.match(script,/p\.set\('status',status\)/);
  assert.match(html,/id="orderCanonical"/);
  assert.match(script,/allCanonical:'全部标准状态'/);
  assert.match(script,/allCanonical:'All canonical statuses'/);
  assert.match(script,/canonicalStatus:'标准状态'/);
  assert.match(script,/canonicalStatus:'Canonical status'/);
  assert.match(script,/sourceStatus:'原始状态'/);
  assert.match(script,/sourceStatus:'Source status'/);
  assert.match(script,/p\.set\('canonical_status',canonical\)/);
  assert.match(script,/canonicalLabels\[lang\]\[x\.canonical_status\]/);
  assert.match(html,/id="orderFrom" type="date"/);
  assert.match(html,/id="orderTo" type="date"/);
  assert.match(script,/from:'开始日期'/);
  assert.match(script,/from:'From'/);
  assert.match(script,/p\.set\('from',from\)/);
  assert.match(script,/p\.set\('to',to\)/);
  assert.match(html,/id="exportOrders"/);
  assert.match(script,/export:'导出 CSV'/);
  assert.match(script,/export:'Export CSV'/);
  assert.match(script,/p\.set\('format','csv'\)/);
  assert.match(script,/authorization:'Bearer '\+token/);
  assert.match(script,/a\.download='vesper-commerce-orders\.csv'/);
  assert.match(html,/id="refreshSummary"/);
  assert.match(script,/summary:'运营概览'/);
  assert.match(script,/summary:'Operations summary'/);
  assert.match(script,/不受 200 条账本上限影响/);
  assert.match(script,/beyond the 200-row ledger limit/);
  assert.match(script,/Number\(x\.amount_minor\)\/100/);
  assert.match(html,/id="inventoryForm"/);
  assert.match(html,/id="lowStockOnly" type="checkbox"/);
  assert.match(script,/inventoryTitle:'库存与低库存预警'/);
  assert.match(script,/inventoryTitle:'Inventory and low-stock alerts'/);
  assert.match(script,/inventoryFields=\['sku','available_quantity','reorder_point'\]/);
  assert.match(script,/async function inventory\(\).*?\/api\/commerce\/inventory/);
  assert.match(script,/p\.set\('low_stock','true'\)/);
  assert.match(script,/inventoryUpdated:'已更新 \{n\} 个 SKU。'/);
  assert.match(script,/inventoryUpdated:'Updated \{n\} SKUs.'/);
  assert.match(html,/id="refreshInventorySummary"/);
  assert.match(script,/inventorySummary:'跨店铺 SKU 汇总'/);
  assert.match(script,/inventorySummary:'Cross-shop SKU summary'/);
  assert.match(script,/async function inventorySummary\(\).*?\/api\/commerce\/inventory-summary/);
  assert.match(script,/x\.low_stock_shop_count/);
  assert.match(script,/x\.shop_count/);
  assert.match(html,/id="exportLowStock"/);
  assert.match(script,/exportLowStock:'导出低库存 CSV'/);
  assert.match(script,/exportLowStock:'Export low-stock CSV'/);
  assert.match(script,/p\.set\('low_stock','true'\);p\.set\('format','csv'\)/);
  assert.match(script,/a\.download='vesper-commerce-low-stock\.csv'/);
});
test('commerce UI rejects unsafe import sizes and duplicate field mappings before the API call',()=>{
  assert.match(script,/file\.size>32768/);
  assert.match(script,/csvRows\.length>100/);
  assert.match(script,/new Set\(mapped\)\.size!==mapped\.length/);
  for(const code of ['file_too_large','too_many_rows','duplicate_mapping','body_too_large']){
    assert.match(script,new RegExp(code));
  }
});
